SIGNING_KEY="GBBHQ7H4V6RRORKYLHTCAWP6MOHNORRFJSDPXDFYDGJB2LPZUFPXUEW3"
HORIZON_URL="https://horizon.domain.com"
ACCOUNTS=[
"GBVRHSJCYHH3TSAM6WRG62TTJX7T6QZSMRNWJCUAA64VPBAQH5MJ24YZ",
"GDISTZCMYHVKXHOA4VOTF2KJIAVI3I6X4BNL5CCD4JX25BULFVH5GBEB",
"GBTGLUZW7ZVR37LQAN6BJNJIXEJNT3QVIWG2WHP6DFJUYJHHX4F3CPMT"
]
VERSION="2.0.0"

[DOCUMENTATION]
ORG_NAME="ABZZDEV"
ORG_URL="https://www.abzzdev.github.io"
ORG_LOGO="https://abzzdev.github.io/favicon-96x96.png"
ORG_DESCRIPTION="Crypto Enthuisast"
ORG_TWITTER="abzzdev117"
ORG_GITHUB="abzzdev"
ORG_OFFICIAL_EMAIL="abzzdev@gmail.com"

[[PRINCIPALS]]
name="ABZZDEV"
email="abzzdev@gmail.com"
twitter="abzzdev117"
github="abzzdev"

[[CURRENCIES]]
code="ABZZCOIN"
issuer="GBVRHSJCYHH3TSAM6WRG62TTJX7T6QZSMRNWJCUAA64VPBAQH5MJ24YZ"
display_decimals=4
is_asset_anchored=false